DROP TABLE IF EXISTS B2C_PRDCT;
DROP TABLE IF EXISTS B2C_BRND;
DROP TABLE IF EXISTS B2C_CLR;
DROP TABLE IF EXISTS B2C_PRDCT_CTGR;

CREATE TABLE PRODUCTCATALOG_BRAND (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL
);


CREATE TABLE PRODUCTCATALOG_COLOR (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL
);


CREATE TABLE PRODUCTCATALOG_PRODUCTCATEGORY (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL
);


CREATE TABLE PRODUCTCATALOG_PRODUCT(
  id INT AUTO_INCREMENT  PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL,
  QUANTITY INT NOT NULL,
  SIZE VARCHAR(5) NOT NULL,
  PRICE INT NOT NULL,
  BRAND_ID INT NOT NULL,
  foreign key (BRAND_ID) references PRODUCTCATALOG_BRAND(ID),
  COLOR_ID INT NOT NULL,
  foreign key (COLOR_ID) references PRODUCTCATALOG_COLOR(ID),
  PRODUCT_CATEGORY_ID INT NOT NULL,
  foreign key (PRODUCT_CATEGORY_ID) references PRODUCTCATALOG_PRODUCTCATEGORY(ID)
);